export default {
    REQUIRE_CSS: 'REQUIRE_CSS',
    REQUIRE_INLINE_CSS: 'REQUIRE_INLINE_CSS',
    REQUIRE_JS: 'REQUIRE_JS',
    SET_LEFT_MENU: 'SET_LEFT_MENU',
    SET_PAGE_TITLE: 'SET_PAGE_TITLE',
    SELECT_TOP_MENU: 'SELECT_TOP_MENU',
    USE_BOOTSTRAP_LAYOUT: 'USE_BOOTSTRAP_LAYOUT',
    USE_BOOTSTRAP_FULLY_RESPONSIVE: 'USE_BOOTSTRAP_FULLY_RESPONSIVE'
};
